#!/usr/bin/env zsh

cp ~/.zshrc .
cp ~/.zshenv .
cp ~/.zprofile .
cp ~/.profile .

rm -rf .config
mkdir .config
cp -r ~/.config/kitty .config
rm -rf .config/docker # Docker may store credentials inside this folder

rm -rf tools
mkdir tools
cp -r ~/tools .
