#!/usr/bin/env zsh

ROOT=$(pwd)
mkdir .backup 2> /dev/null
cd .backup

NOW=$(date +'%Y-%m-%dT%H:%M:%S%z')
mkdir $NOW
cd $NOW

$ROOT/sync_backup.sh
echo "current config backed up to $(pwd)"
echo "contents:"
eza -Ta

cd $ROOT
cp .zshrc ~
cp .zshenv ~
cp .zprofile ~
cp .profile ~

mkdir ~/.config 2> /dev/null
cp -r .config/kitty ~/.config

mkdir ~/tools 2> /dev/null
cp -r tools ~/tools
