#!/usr/bin/env zsh

# Use the `analysis.fossa.com` API to resolve, get metadata, and download a project.
# usage: . fetcher {resolve|getMetadata|download} <locator>

case "$1" in
    "resolve")
        xh "https://analysis.fossa.com/api/v1/project/$(urlencode $2)/resolve"
        ;;
    "getMetadata")
        xh "https://analysis.fossa.com/api/v1/project/$(urlencode $2)/metadata"
        ;;
    "download")
        URL=$(xh "https://analysis.fossa.com/api/v1/project/$(urlencode $2)/resolve" | jaq ".download_url" -r)
        curl $URL
        ;;
    *)
        echo "Usage: $0 {resolve|getMetadata|download} <locator>"
        exit 1
        ;;
esac
